spring:
  datasource:
    # h2데이터베이스입니다. 연결을 하지않아도 실행되는건 url: jdbc:h2:mem:test
    # 연결을 해야 실행되는 건 jdbc:h2:tcp://localhost/~/jpashop 입니다.
#    url: jdbc:h2:tcp://localhost/~/jpashop
    url: jdbc:h2:mem:test
    username: sa
    password:
    driver-class-name: org.h2.Driver

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 124384706033-9avgti6ejn1bkfgdm4duqi8afhrjcbli.apps.googleusercontent.com
            client-secret: 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
            scope:
              - profile
              - email
          naver:
            client-id: tsHGWjGp9yw_NvJ8lixD
            client-secret: IdHYByPccp
            client-name: Naver
            redirect-uri: "http://localhost:8080/login/oauth2/code/naver"
            authorization-grant-type: authorization_code
            scope:
              - name
              - email
          kakao:
            client-id: cf744d85652baace22beae1a1901cde5
            client-secret: nD3gssyAA0iGhgUcaD306TKOeT5FiV81
            client-name: Kakao
            # Spring security 5.6 이후로 변경되었나 봅니다. (POST → client_secret_post) 로 변경됐네요.
            client-authentication-method: Post
            redirect-uri: "http://localhost:8080/login/oauth2/code/kakao"
            authorization-grant-type: authorization_code
            scope:
              - profile_nickname
              - account_email
        provider:
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000 #최적화 옵션

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace